name: 'handle-image-version'
description: 'java'
inputs:
  arg1:
    description: '引数１'
    required: false
    default: '1個目の引数@Default'
  arg2:
    description: '引数２'
    required: false
  arg3:
    description: '引数３'
    required: false

runs:
  using: "composite"
  steps:
    - run: >-
        ${{ github.action_path }}/main.sh
        "${{ inputs.arg1 }}" "${{ inputs.arg2 }}" "${{ inputs.arg3 }}"
      shell: bash
    - run: cd ${{ github.action_path }} && ls -l && pwd
      shell: bash

