name: 'handle-image-version'
description: 'java'
inputs:
  java_version:
    description: 'java version'
    required: false
    default: 'latest'
  test_str:
    description: '起動時に出力する文字列'
    required: true
runs:
  using: "composite"
  steps:
    - run: pwd
      shell: bash
    - run: ls -a
      shell: bash
    - run: env
      shell: bash
    - run: docker ps
      shell: bash
