name: environments check

on:
  workflow_dispatch:

env:
  # composite/conatiner actionに渡る
  CUSTOM_ENV1: "独自環境変数: env"

jobs:
  test:
    env:
      # composite/conatiner actionに渡る
      CUSTOM_ENV2: "独自環境変数: jobs.<job_id>.env"
    name: test-action
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/composite-action/
        env:
          # composite actionに渡る
          CUSTOM_ENV3: "独自環境変数: jobs.<job_id>.steps[*].env"
      - uses: ./.github/docker-action/
        env:
          # conatiner actionに渡る
          CUSTOM_ENV4: "独自環境変数: jobs.<job_id>.steps[*].env"
        with:
          entrypoint: env
